services:
  - type: web
    name: mogger-bot
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    runtime: python3
    plan: free
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: ALLOWED_USERS
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.18
